version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies"]
    ignore:
      - dependency-name: "n8n-core"
      - dependency-name: "n8n-workflow"
