import type { Type } from "arktype";
import type { App } from "../app";
import type { WorkflowProps } from "./workflow";

export interface ImportedWorkflowProps<Input extends Type, Output extends Type>
	extends Pick<WorkflowProps<Input, Output>, "inputSchema" | "outputSchema"> {
	/**
	 * Id of the workflow generated by n8n-kit (used in tags or visible in the CLI tables)
	 *
	 * Use this if you want the CLI to resolve the workflow id automatically
	 */
	hashId?: string;

	/**
	 * Id of the workflow in n8n
	 */
	n8nWorkflowId?: string;
}

export class ImportedWorkflow<
	Input extends Type = any,
	Output extends Type = any,
> {
	public constructor(
		app: App,
		public readonly props: ImportedWorkflowProps<Input, Output>,
	) {
		app.add(this);
		if (!props.hashId && !props.n8nWorkflowId) {
			throw new Error("Either hashId or n8nWorkflowId must be provided");
		}
	}
}
